// 上传限制
export const UPLOAD = {
  MAX_IMAGE_WIDTH: 1280, //为了满足ios最大canvas像素限制
  MAX_IMAGE_HEIGHT: 1280,
  MAX_IMAGE_WIDTH_PC: 2048,
  MAX_IMAGE_HEIGHT_PC: 2048,
  MAX_VIDEO_WIDTH: 1920,
  MAX_VIDEO_HEIGHT: 1920,
  MIN_VIDEO_WIDTH: 160,
  MIN_VIDEO_HEIGHT: 160,
  MAX_DURATION_BETA: 10,
  MAX_IMAGE_SIZE: 10 * 1024 * 1024,
  BACK_MAX_SIZE: 4 * 1024 * 1024,
  MAX_GIF_SIZE: 15 * 1024 * 1024,
  MAX_VIDEO_SIZE_BETA: 500,
  ALLOWED_EXTS: ['avi', 'mov', 'mp4', 'jpg', 'jpeg', 'png', 'gif'],
  ALLOWED_VIDEO_TYPES: ['x-msvideo', 'quicktime', 'mp4', 'mov']
}

export const UPLOAD_RULES = {
  IMAGE_SIZE_ERROR: 'image_size_error',
  GIF_SIZE_ERROR: 'gif_size_error',
  VIDEO_SIZE_ERROR: 'video_size_error',
  IMAGE_METRIC_ERROR: 'image_metric_error',
  VIDEO_METRIC_ERROR: 'video_metric_error',
  VIDEO_DURATION_ERROR: 'video_duration_error',
  FILE_FORMAT_ERROR: 'file_format_error'
}

export enum FILE_TYPE {
  MATERIAL = 'MATERIAL',
  FACE = 1,
  RESOURCE_COMPLAINT_PROOF,
  BANNER_COVER,
  SPLASH_SCREEN,
  APP_VERSION,
  AVATAR,
  PRE_FACE_SHIFT,
  PUBLIC_MATERIAL,
  PUBLIC_MATERIAL_COVER,
  DEMO,
  FEATURE_ITEM_COVER,
  TEMPORARY_FACE,
  TEMPORARY_MATERIAL,
  PARSE_FACE,
  INPAINTING_IMAGE = 'INPAINTING_IMAGE',
  INPAINTING_IMAGE_MASK = 'INPAINTING_IMAGE_MASK',
  EXTEND_IMAGE_COMBINED_IMAGE_MASK = 'EXTEND_IMAGE_COMBINED_IMAGE_MASK',
  EXTEND_IMAGE_ORIGIN_IMAGE = 'EXTEND_IMAGE_ORIGIN_IMAGE',
  EXTEND_IMAGE_COMBINED_IMAGE = 'EXTEND_IMAGE_COMBINED_IMAGE',
  REMOVE_BACKGROUND_ORIGIN_IMAGE = 'REMOVE_BACKGROUND_ORIGIN_IMAGE',
  SUPER_RESOLUTION_ORIGIN_IMAGE = 'SUPER_RESOLUTION_ORIGIN_IMAGE',
  ANIME_STYLIZE_PHOTO = 'ANIME_STYLIZE_PHOTO',
  HUMAN_FOUNDATION = 'HUMAN_FOUNDATION'
}